#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     infrared,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     weight,         sensorHiTechnicTouchMux)
#pragma config(Sensor, S4,     touch,          sensorTouch)
#pragma config(Motor,  motorA,          motor_popcorn, tmotorNXT, openLoop, reversed)
#pragma config(Motor,  motorB,          motor_B,       tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          motor_C,       tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motor_L,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motor_R,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motor_lift,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motor_G,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    servo_IR,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo_claw,           tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo_ramp,           tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
// Code generated by the 'ROBOTC' configuration wizard.
#include "JoystickDriver.c"
#include "hitechnic-irseeker-v2.h"
#include "typedefs.h"
#include "global vars.h"
#include "enums.h"
#include "structs.h"
#include "low-level functions.h"
#include "high-level functions.h"
#include "subroutines.h"



void initializeRobot()
{
	// Place code here to init servos to starting positions.
	// Sensors are config'ed and setup by RobotC (need to stabalize).
	// Also add any settings that need to be set (other than global
	// variables), such as max PID speed, servo update rate, etc.

	Servo_SetSpeed(servo_IR, 10);	// maximum speed!
	Servo_SetSpeed(servo_claw, 10);	// maximum speed!
	Servo_SetSpeed(servo_ramp, 10);	// maximum speed!

	Servo_Rotate(servo_IR, g_IRServoExtended);		// fold back up after start of tele-op
	Servo_Rotate(servo_claw, g_clawServoExtended);	// keep it straight out after tele-op
	Servo_Rotate(servo_ramp, g_rampServoDefault);	// stop ramp from deploying


	Motor_SetMaxSpeed(g_FullMotorPower);

	Motor_ResetEncoder(motor_L);
	Motor_ResetEncoder(motor_R);
	Motor_ResetEncoder(motor_lift);

	nMotorEncoder[motor_lift] = 0;


	//HTIRS2setDSPMode(infrared, g_IRsensorMode);


	Time_Wait(10);

	return;
}



task main()
{


	//// These will be used later and are declared here to save from having to
	//// declare them every single loop.
	//int IRdirA = 0;
	//int IRdirB = 0;
	//int IRdirC = 0;
	//int IRdirD = 0;
	//int IRdirE = 0;



	waitForStart();

	initializeRobot();



	// The amount of time the robot...

	// ...moves forward at an angle.
	const int forwardTimeA	= 150;
	// ...turns to line up perpendicular to the center rack.
	const int turnTimeB		= 40;
	// ...drives up to the peg before lifting the lift up.
	const int forwardTimeC	= 155;
	// ...lifts the claw to put a ring on.
	const int liftTimeF		= 79;
	// ...moves forward, putting the ring onto the peg
	const int forwardTimeG	= 65;
	// ...lowers its lift to get rid of the ring.
	const int liftTimeH		= 55;
	// ...backs up and gets ready to go to a dispenser.
	const int backwardTimeI	= 300;

	Move_Forward	(forwardTimeA, g_AccurateMotorPower);
	Turn_Left		(turnTimeB, g_AccurateMotorPower, g_AccurateMotorPower);
	Move_Forward	(forwardTimeC, g_AccurateMotorPower);
	Lift_Lift		(liftTimeF, g_AccurateMotorPower);
	Move_Forward	(forwardTimeG, g_AccurateMotorPower);
	StartTask(sub_MOO);
	// Lift power is negative so that the lift goes DOWN, not UP.
	Lift_Lift		(liftTimeH, (-1) * g_AccurateMotorPower);
	Move_Backward	(backwardTimeI, g_AccurateMotorPower);
	Turn_Left		(turnTimeB, g_AccurateMotorPower, g_AccurateMotorPower);


	//Turn_Left(g_TurnTimeA, 100, 100);
	//Move_Forward(g_ForwardTimeA, 100);
	//Time_Wait(50);

	////HTIRS2readAllDCStrength(infrared, IRdirA, IRdirB, IRdirC, IRdirD, IRdirE);

	//if ( (IRdirA+IRdirB+IRdirC+IRdirD+IRdirE) > g_IRthreshold )
	//{
	//	Turn_Left(g_TurnTimeB, g_AccurateMotorPower, g_AccurateMotorPower);
	//	Move_Forward(g_ForwardTimeB, g_AccurateMotorPower);
	//	Lift_Lift(g_LiftTimeB, g_AccurateMotorPower);
	//}
	//else
	//{
	//	Move_Forward(g_ForwardTimeC, g_AccurateMotorPower);
	//	Time_Wait(50);
	//	//HTIRS2readAllACStrength(infrared, IRdirA, IRdirB, IRdirC, IRdirD, IRdirE);
	//	if ( (IRdirA+IRdirB+IRdirC+IRdirD+IRdirE) > g_IRthreshold )
	//	{
	//		Turn_Left(g_TurnTimeD, g_AccurateMotorPower, g_AccurateMotorPower);
	//		Move_Forward(g_ForwardTimeD, g_AccurateMotorPower);
	//		Lift_Lift(g_LiftTimeD, g_AccurateMotorPower);
	//	}
	//	else
	//	{
	//		Move_Forward(g_ForwardTimeE, g_AccurateMotorPower);
	//		Turn_Left(g_TurnTimeF, g_AccurateMotorPower, g_AccurateMotorPower);
	//		Move_Forward(g_ForwardTimeF, g_AccurateMotorPower);
	//		Lift_Lift(g_LiftTimeF, g_AccurateMotorPower);
	//	}
	//}
}
