#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     sensor_1,       sensorNone)
#pragma config(Sensor, S3,     sensor_2,       sensorNone)
#pragma config(Sensor, S4,     sensor_3,       sensorNone)
#pragma config(Motor,  motorA,          motor_claw,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          motor_B,       tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          motor_C,       tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motor_L,       tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motor_R,       tmotorTetrix, PIDControl)
// Code generated by 'ROBOTC' configuration wizard
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "typedefs-6121.h"
#include "global vars-6121.h"
#include "enums-6121.h"
#include "structs-6121.h"
#include "low-level functions-6121.h"
#include "high-level functions-6121.h"
#include "subroutines-6121.h"


void initializeRobot()
{
	// Place code here to init servos to starting positions.
	// Sensors are auto-config'ed and setup by RobotC. They may need to stabilize.
	return;
}


task main()
{
	initializeRobot();
	waitForStart(); // Wait for the beginning of autonomous phase.

	while (true)
	{
		// Code.
	}
}
