#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2, HTIRS2, sensorI2CCustom)
#pragma config(Sensor, S3,     sensor_2,       sensorNone)
#pragma config(Sensor, S4,     sensor_3,       sensorNone)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motor_L,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motor_R,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorLiftL,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorLiftR,    tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Code generated by 'ROBOTC' configuration wizard
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "../Header Files/typedefs-6121.h"
#include "../Header Files/global vars-6121.h"
#include "../Header Files/enums-6121.h"
#include "../Header Files/structs-6121.h"
#include "../Header Files/low-level functions-6121.h"
#include "../Header Files/high-level functions-6121.h"
#include "../Header Files/subroutines-6121.h"
#include "../Header Files/driver/hitechnic-irseeker-v2.h"


void initializeRobot(){
	//IR initialization code from example found at http://www.usfirst.org/sites/default/files/uploadedFiles/Robotics_Programs/FTC/FTC_Documents/Using_the_IR_Seeker.pdf

	/*******************initialize the IR sensor*******************/
	tHTIRS2DSPMode mode = DSP_1200;
	// attempt to set to DSP mode.
	if (HTIRS2setDSPMode(HTIRS2, mode) == 0){
		// unsuccessful at setting the mode.
		// display error message.
		eraseDisplay();
		nxtDisplayCenteredTextLine(0, "ERROR!");
		nxtDisplayCenteredTextLine(2, "Init failed!");
		nxtDisplayCenteredTextLine(3, "Connect sensor");
		nxtDisplayCenteredTextLine(4, "to Port 1.");
		// make a noise to get their attention.
		PlaySound(soundBeepBeep);
		wait10Msec(300);
		return;
	}


}


task main()
{
	initializeRobot();
	waitForStart(); // Wait for the beginning of autonomous phase.

	Move_Forward(100, 50);

	while (true)
	{
		Turn_Left(100, g_FullDrivePower, g_FullDrivePower);
	}
}
