#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     sensor_1,       sensorNone)
#pragma config(Sensor, S3,     sensor_2,       sensorNone)
#pragma config(Sensor, S4,     sensor_3,       sensorNone)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     liftL,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     liftR,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     driveR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     driveL,        tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Code generated by 'ROBOTC' configuration wizard
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "global vars-6121.h"
#include "enums-6121.h"
#include "low-level functions-6121.h"
#include "high-level functions-6121.h"

task main()
{
	waitForStart();

	int powerL = 0;
	int powerR = 0;
	int liftPower = 0;

	while (true)
	{
		Joystick_UpdateData();

		// These should be zeroed after every loop. In the case that there
		// isn't input, the robot won't keep moving at the last speed it had.
		powerL = 0;
		powerR = 0;

		// Y-axis code:
		if ( 	abs(joystick.joy1_y1) > g_JoystickThreshold ||
				abs(joystick.joy1_y2) > g_JoystickThreshold )
		{
			powerL = joystick.joy1_y1;
			powerR = joystick.joy1_y2;
		}

		// Last check: if LB/RB is pressed, fine-tune the power level.
		if ( (Joystick_Button(BUTTON_LB)||Joystick_Button(BUTTON_RB)) ==true )
		{
			powerL /= g_FineTuneFactor;
			powerR /= g_FineTuneFactor;
		}
		if (Joystick_Button(BUTTON_X)) {
			liftPower = 75;
		}
		else if (Joystick_Button(BUTTON_A)) {
			liftPower = -75;
		}
		else {
			liftPower = 0;
		}
		if (Joystick_Button(BUTTON_LT)) {
			liftPower *= 2;
		}

		Motor_SetPower(driveL, powerL);
		Motor_SetPower(driveR, powerR);
		Motor_SetPower(liftL, liftPower);
		Motor_SetPower(liftR, liftPower);
	}
}
