#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     sensor_1,       sensorNone)
#pragma config(Sensor, S3,     sensor_2,       sensorNone)
#pragma config(Sensor, S4,     sensor_3,       sensorNone)
#pragma config(Motor,  motorA,          motor_claw,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          motor_B,       tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          motor_C,       tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motor_L,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motor_R,       tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    servo_base,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo_elbow,          tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
// Code generated by 'ROBOTC' configuration wizard
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "typedefs-6121.h"
#include "global vars-6121.h"
#include "enums-6121.h"
#include "structs-6121.h"
#include "low-level functions-6121.h"
#include "high-level functions-6121.h"
#include "subroutines-6121.h"



void initializeRobot()
{
	// Place code here to init servos to starting positions.
	// Sensors are auto-config'ed and setup by RobotC.
	// They may need to stabilize.
	return;
}


task main()
{
	initializeRobot();
	waitForStart();

	while (true)
	{
		Joystick_UpdateData();



		// Logarithmic control probably won't be implemented anytime soon.
		// Also need to stop using the `joystick` struct and switch to the
		// encapsulated version (Joystick_Joystick(...)).

		// These should be zeroed after every loop. In the case that there
		// isn't input, the robot won't keep moving at the last speed it had.
		powerL = 0;
		powerR = 0;

		// Y-axis code:
		if ( 	abs(joystick.joy1_y1) > g_JoystickThreshold ||
				abs(joystick.joy1_y2) > g_JoystickThreshold )
		{
			powerL = Math_ToLogarithmic(joystick.joy1_y1);
			powerR = Math_ToLogarithmic(joystick.joy1_y2);
		}

		// Last check: if LB/RB is pressed, fine-tune the power level.
		if ( (Joystick_Button(BUTTON_LB)||Joystick_Button(BUTTON_RB)) ==true )
		{
			powerL /= g_FineTuneFactor;
			powerR /= g_FineTuneFactor;
		}

		Motor_SetPower(motor_L, powerL);
		Motor_SetPower(motor_R, powerR);



	}
}
