#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     infrared_L,     sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     infrared_R,     sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          claw_L,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          claw_R,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          release_ramp,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motor_L,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motor_R,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motor_lift,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motor_G,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Code generated by 'ROBOTC' configuration wizard
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "enums.h"
#include "low-level functions.h"


task main()
{
	while (true)
	{
		if (nNxtButtonPressed == 3)	//orange button
		{
			Motor_SetPower(motor_L, -100);
			Motor_SetPower(motor_R, -100);
			Time_Wait(50);
			Motor_Stop(motor_L);
			Motor_Stop(motor_R);
		}
		if (nNxtButtonPressed == 2)	//left arrow button
		{
			Motor_SetPower(motor_L, -100);
			Motor_SetPower(motor_R, 100);
			Time_Wait(50);
			Motor_Stop(motor_L);
			Motor_Stop(motor_R);
		}
		if (nNxtButtonPressed == 1)	//right arrow button
		{
			Motor_SetPower(motor_L, 100);
			Motor_SetPower(motor_R, -100);
			Time_Wait(50);
			Motor_Stop(motor_L);
			Motor_Stop(motor_R);
		}
	}
}
