#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     infrared_L,     sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     infrared_R,     sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          claw_L,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          claw_R,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          release_ramp,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motor_L,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motor_R,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motor_lift,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motor_G,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
// Code generated by 'ROBOTC' configuration wizard
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "enums.h"
#include "low-level functions.h"



void initializeRobot()
{
	// Place code here to init servos to starting positions.
	// Sensors are auto-config'ed and setup by RobotC.
	// They may need to stabilize.
	return;
}


task main()
{
	initializeRobot();
	waitForStart();

	while (true)
	{
		Joystick_UpdateData();


		// Drive motors' power assignment:
		int motorL = 0;
		int motorR = 0;

		if ( Joystick_Button(BUTTON_LB)==1 || Joystick_Button(BUTTON_RB)==1 )
		{
			motorL = -1 * joystick.joy1_y1 / 4;
			motorR = -1 * joystick.joy1_y2 / 4;
		}
		else
		{
			motorL = -1 * joystick.joy1_y1;
			motorR = -1 * joystick.joy1_y2;
		}

		Motor_SetPower( motor_L, motorL );
		Motor_SetPower( motor_R, motorR );


		// Lift motor's power assignment
		if ( Joystick_Button(BUTTON_B)==1 )
		{
			Motor_SetPower( motor_lift, 100 );
			Time_Wait( 100 );
			Motor_Stop( motor_lift );
		}
		if ( Joystick_Button(BUTTON_A)==1 )
		{
			Motor_SetPower( motor_lift, -100 );
			Time_Wait( 100 );
			Motor_Stop( motor_lift );
		}
	}
}
