#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     infrared,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     weight,         sensorLightInactive)
#pragma config(Sensor, S4,     touch,          sensorTouch)
#pragma config(Motor,  motorA,          motor_A,       tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          motor_B,       tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          motor_C,       tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motor_L,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motor_R,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motor_lift,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motor_G,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    servo_IR,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo_force,          tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo_ramp,           tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
// Code generated by 'ROBOTC' configuration wizard
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "enums.h"
#include "low-level functions.h"



void initializeRobot()
{
	Servo_Rotate(servo_IR, 230);
	return;
}


task main()
{
	initializeRobot();
	waitForStart();

	while (true)
	{
		Joystick_UpdateData();


		// Drive motors' power assignment:
		int motorL = 0;
		int motorR = 0;

		if ( Joystick_Button(BUTTON_LB)==1 || Joystick_Button(BUTTON_RB)==1 )
		{
			motorL = -1 * joystick.joy1_y1 / 4;
			motorR = -1 * joystick.joy1_y2 / 4;
		}
		else
		{
			motorL = -1 * joystick.joy1_y1;
			motorR = -1 * joystick.joy1_y2;
		}

		Motor_SetPower( motor_L, motorL );
		Motor_SetPower( motor_R, motorR );


		// Lift motor's power assignment
		if ( Joystick_Button(BUTTON_B)==1 )
		{
			Motor_SetPower( motor_lift, 100 );
			Time_Wait( 100 );
			Motor_Stop( motor_lift );
		}
		if ( Joystick_Button(BUTTON_A)==1 )
		{
			Motor_SetPower( motor_lift, -100 );
			Time_Wait( 100 );
			Motor_Stop( motor_lift );
		}
	}
}
