#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     infrared,       sensorI2CCustom)
#pragma config(Sensor, S3,     color,          sensorCOLORFULL)
#pragma config(Sensor, S4,     ultrasonic,     sensorSONAR)
#pragma config(Motor,  motorA,          motor_A,       tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          motor_B,       tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          motor_C,       tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motor_L,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motor_R,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motor_lift,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motor_G,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    servo_IR,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo_claw,           tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo_ramp,           tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    servo_D,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    servo_E,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_6,    servo_F,              tServoStandard)
// Code generated by the 'ROBOTC' configuration wizard.
#include "JoystickDriver.c"
#include "IR-driver.h"
#include "enums.h"
#include "global vars.h"



void initializeRobot()
{
	// Sensors are config'ed and setup by RobotC (need to stabalize).

	servoChangeRate[servo_IR]	= 20;		// relatively high speed.
	servoChangeRate[servo_claw]	= 20;		// relatively high speed.
	servoChangeRate[servo_ramp]	= 0;		// ??? Might not work anymore.

	servo[servo_IR]		= g_IRServoLowered;		// it gets in the way
	servo[servo_claw]	= g_clawServoFolded;	// servo bracket gets bent
	servo[servo_ramp]	= g_rampServoDefault;	// stops ramp from deploying

	nMaxRegulatedSpeedNxt = g_FullPower;

	bFloatDuringInactiveMotorPWM = false;

	return;
}



task main()
{
	waitForStart();
	initializeRobot();



	while (true)
	{
		getJoystickSettings(joystick);

		// All of the code is for CONTROLLER_1.
		if ( joystick.joy1_TopHat != (-1) )
		{
			switch ( joystick.joy1_TopHat )
			{

				// Operate lift at full power if F/B.
				case DIRECTION_F:
					motor[motor_lift] = g_FullLiftPower;
					break;
				case DIRECTION_B:
					motor[motor_lift] = (-1)*g_FullLiftPower;
					break;
			}
		}
		else
			motor[motor_lift] = 0;


		// JOYSTICKS INPUT:--------------------------------------------------|>
		if ( abs(joystick.joy1_y1) > g_JoystickThreshold )
			motor[motor_L] = joystick.joy1_y1;
		else
			motor[motor_L] = 0;

		if ( abs(joystick.joy1_y2) > g_JoystickThreshold )
			motor[motor_R] = joystick.joy1_y2;
		else
			motor[motor_R] = 0;


		// BUTTONS INPUT:--------------------------------------------------|>
		if ( joystick.joy1_Buttons != false )
		{
			// Buttons LT/RT fine-tune the lift.
			if ( joy1Btn(BUTTON_RT)==true )
				motor[motor_lift] = g_FullLiftPower/g_FineTuneFactor;
			if ( joy1Btn(BUTTON_LT)==true )
				motor[motor_lift] = (-1)*g_FullLiftPower/g_FineTuneFactor;
		}
	}
}
